version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: scaffold_dev_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "${DB_PORT}:5432"
