version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: scaffold_dev_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "${DB_PORT}:5432"
  sonarqube:
    image: sonarqube:latest
    container_name: scaffold_dev_sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/postgres
      - SONARQUBE_JDBC_USERNAME=postgres
      - SONARQUBE_JDBC_PASSWORD=postgres
    ports:
      - "${SONARQUBE_PORT}:9000"